import type { Metadata } from 'next';
import Inicio from './Inicio/page';
import './css/style.css';

export const metadata: Metadata = {
  title: 'DoReMi',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <main>
          <Inicio/>
          {children}
        </main>
      </body>
    </html>
  );
}
